### ISSUE TITLE
Setting project-vc-extra-root-markers to find Cargo.toml for projects

### ISSUE THREAD

**Issue by jgarte** [ntBre/.emacs#1]
What are your thoughts on using project.el instead of projectile with eglot?

There's the following thread that mentions setting `project-vc-extra-root-markers` in order to correctly discover Rust projects with eglot.

https://github.com/joaotavora/eglot/issues/98#issuecomment-1751703252

**Comment by ntBre** [comment]
That's a very timely question because as a result of [this bug](https://lists.gnu.org/archive/html/bug-gnu-emacs/2024-02/msg00249.html) I reported in Emacs, I spent the last couple of weeks using project.el in my main config instead of projectile. Overall I like it pretty well, and it works perfectly for simple cases, but I haven't figured out how to use it for nested projects. As a result I actually reverted back to projectile this morning. I'll take a look at this thread and definitely save it in case I try project.el again in the future, but I think projectile "just works" well enough that I'll stick with it for now.

**Comment by jgarte** [comment]
Thanks for the user experience report. I might end up using projectile if I have to work with nested projects and stuff doesn't work with project.el.

**Comment by ntBre** [comment]
No problem. I would like to move to more of the built-in packages, especially project.el instead of projectile and eglot instead of lsp-mode (I still use lsp-mode in my main config, despite using eglot here), but I just haven't put the time into finding or adding the features needed to replicate my existing workflows. Thanks again for this link, I think it will be helpful next time I look at project.el!

**Comment by jgarte** [comment]
Do you mind sharing your current config that has the lsp stuff in it? I've also been dabbling with lsp-mode for rust development and would like to compare.

**Comment by ntBre** [comment]
This should be my whole rust-mode config:

```emacs-lisp
(require 'rust-ts-mode)
;; these are provided by rust-mode, but I want to use them in rust-ts-mode
(require 'rust-utils)
(define-key rust-ts-mode-map (kbd "C-c C-d") #'rust-dbg-wrap-or-unwrap)

;;; rust
(use-package rust-mode
  :ensure t
  :hook ((rust-mode . flycheck-mode)
		 (rust-mode . hs-minor-mode))
  :bind (:map rust-mode-map
			  ("<f6>"  . my/rust-format-buffer)
			  ("C-c 6" . my/rust-format-buffer))
  :bind (:map rust-ts-mode-map
			  ("<f6>"  . my/rust-format-buffer)
			  ("C-c 6" . my/rust-format-buffer))
  :config
  (require 'rust-rustfmt)
  (setq rust-format-show-buffer nil)
  (defun my/rust-format-buffer ()
    (interactive)
    (rust-format-buffer)
    (save-buffer)))

(defun cargo-add (pkg)
  (interactive "Mcargo add ")
  (call-process-shell-command
   (format "cargo add %s" pkg)))

(require 'compile)

(defvar rustc-panic-compilation-regexps
  '("thread '[^']+' panicked at \\(\\(.*\\):\\([0-9]+\\):\\([0-9]+\\)\\)"
	2 3 4 nil 1)
  "Specifications for matching panics in rustc invocations. See
`compilation-error-regexp-alist' for help on their format.")

(add-to-list 'compilation-error-regexp-alist 'rustc-panic)
(add-to-list 'compilation-error-regexp-alist-alist
			 (cons 'rustc-panic rustc-panic-compilation-regexps))
```

It's a bit messy, but I think the whole bottom section was fixed in rust-mode as of a few days ago ([rust-mode#510](https://github.com/rust-lang/rust-mode/pull/510)).

And this should be my lsp-mode config:

```emacs-lisp
(use-package lsp-mode
  :ensure t
  :hook ((rust-mode      . lsp-deferred)
	 (rust-ts-mode   . lsp-deferred)
	 (go-mode        . lsp-deferred)
	 (python-mode    . lsp-deferred)
	 (python-ts-mode . lsp-deferred)
	 (f90-mode       . lsp-deferred)
	 (fortran-mode   . lsp-deferred))
  :bind (:map lsp-mode-map
	      ("C-c d" . lsp-describe-thing-at-point)
	      ("C-c a" . lsp-execute-code-action)
	      ("C-c f" . flycheck-list-errors))
  :config
  ;; rust
  (require 'lsp-rust)
  (setq lsp-rust-analyzer-completion-add-call-parenthesis nil
	lsp-rust-analyzer-proc-macro-enable t
	lsp-rust-analyzer-cargo-watch-command "clippy")

  ;; go
  (require 'lsp-go)
  (setq lsp-go-analyses
	'((fieldalignment . t)
	  (nilness        . t)
	  (unusedwrite    . t)
	  (unusedparams   . t)))
  (setq gofmt-command "goimports")

  ;; treesit integration
  (add-to-list 'lsp-language-id-configuration '(rust-ts-mode . "rust"))
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection "rust-analyzer")
		    :activation-fn (lsp-activate-on "rust")
		    :server-id 'rust-analyzer))

  ;; general
  (define-key lsp-mode-map (kbd "C-c l") lsp-command-map)
  (lsp-enable-which-key-integration t)
  (setq lsp-enable-links nil
	lsp-keep-workspace-alive nil
	lsp-signature-doc-lines 2
	lsp-enable-snippet nil)
  (cl-defmethod lsp-clients-extract-signature-on-hover
    (contents (_server-id (eql rust-analyzer)))
    "from https://github.com/emacs-lsp/lsp-mode/pull/1740 to extract
signature in rust"
    (-let* (((&hash "value") contents)
	    (groups (--partition-by (s-blank? it) (s-lines (s-trim value))))
	    (sig_group (if (s-equals? "```rust" (car (-third-item groups)))
			   (-third-item groups)
			 (car groups)))
	    (sig (--> sig_group
		      (--drop-while (s-equals? "```rust" it) it)
		      (--take-while (not (s-equals? "```" it)) it)
		      (--map (s-trim it) it)
		      (s-join " " it))))
      (lsp--render-element (concat "```rust\n" sig "\n```")))))
```

Again, that bit at the bottom might not be needed anymore, but I remember adding it to get a better documentation snippet on hover. I'm pretty sure it's using some utility functions/macros from an external package, but if you have enough melpa packages installed, they will probably already be available. I also left the Go stuff and some of the hooks for other languages in, just to avoid any copy-paste errors.
